### ISSUE TITLE
limit of upgrade

### ISSUE THREAD

**Issue by thoruimend** [atusmk2/yasumi#1]
so, is it possible to make the limit on post-moonlord? i'm playing with the calamity mod, and moonlord isn't a last boss, imbalance, i make the weapon that kill moonlord for 5 seconds xD
(sorry, if something writed incorrect, my english bad :D)

**Comment by thoruimend** [comment]
i know, in the description was writed about this, but, is it possible to make limit?
like options, something like that

**Comment by atusmk2** [comment]
Actually I was thinking of adding this feature, and so here we are. :D

Added config to set max upgrade as per commit [70cd5b1](https://github.com/atusmk2/yasumi/commit/70cd5b15fed29a7fd6242161f3aba6e3972909f9).

Steam version will be updated soonish, I had network problem right now.

**Comment by thoruimend** [comment]
Thanks, bro!
